name: gallery-ci

on:
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: test-id-for-ci
  GCE_INSTANCE: instance-1
  GCE_INSTANCE_ZONE: asia-east1
  FRONTEND_SERVICE_NAME: gallery-frontend
  BACKEND_SERVICE_NAME: gallery-backend

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build the Docker image
      - name: Build
        run: |-
          docker build -f apps/web/Dockerfile . --tag "gcr.io/$PROJECT_ID/web-$GCE_INSTANCE-image:$GITHUB_SHA" --no-cache
          docker build -f apps/api/Dockerfile . --tag "gcr.io/$PROJECT_ID/api-$GCE_INSTANCE-image:$GITHUB_SHA" --no-cache
