# workflow 名稱
name: Notification

# 什麼情況下觸發 workflow
on:
  # 對於 main branch 建立 Branch 與 Pull Request 時觸發 workflow
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Job 可以循序或平行執行
jobs:
  # 這個 workflow 只有一個 job，名稱為 "build"
  notify:
    # 這個 job 會執行 gcp 上頭
    runs-on: [self-hosted, linux, x64]

    # 作為 Job 的一部分，Steps 會循序執行一連串的動作
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: "Ilshidur/action-discord@0.3.2"
        with:
          args: "The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed."
